CREATE TABLE IF NOT EXISTS keys (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    holder text NOT NULL,
    affiliation text NOT NULL,
    value text NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
)
